---
title   : 'Markets for Visas: A Radical And Fair Solution to Immigration'
author  : 'Andre Assumpcao'
date    : Dec 31, 2018
abstract: TBU.
output  : 
  # word_document: 
  #   reference_docx: template.docx
  pdf_document:
    number_sections: FALSE
---
\clearpage

# Introduction {#intro}

Suppose the NFL Commissioner decides to distribute Super Bowl tickets under a rules-based system. Fans are now required to submit a form with personal information, education levels, current and previous employment, their skills, and answers to questions on why they think they should be given a ticket to attend the Super Bowl. You can quickly see how problematic this system is. The NFL would need additional staff to process the paperwork and assess every applicant against each other, rank them, and finally assign tickets based on internal criteria unbeknownst to applicants.

Alternatively, suppose now the U.S. Citizenship and Immigration Services (USCIS) Director decides to distribute visas under a price system. The USCIS publishes a schedule of visas and their respective prices, applicants review visa conditions, submit forms, and the visa fee to the USCIS. Unless there are red flags with one's application, the USCIS approves the candidate's application and they are allowed entry into the United States. People are also likely to oppose this proposal, fearing that ill-intended individuals will apply and that this policy discriminates against poor people who cannot afford visas.

Why do we generally accept prices mediating the exchange for seats at the Super Bowl but would oppose the rules system? Why do we generally accept rules mediating the exchange for visas in the USCIS but would oppose the price system? This is an inconsistent belief, to say the least. In this essay, I argue that governments should sell visas to prospective immigrants. I supplement the reasoning in Becker,^[Becker, 2011] Hidalgo^[Hidalgo, 2016] and Freiman^[Freiman, 2017] and contribute an utilitarian argument in favor of such markets. In fact, the utilitarian supplement developed here is the missing piece for unifying the support for immigration markets across philosophy and economics. The argument constructed here has four main pillars: (i) visa markets are no less discriminatory than existing policies; (ii) they create compensation mechanisms for negative, localized distributional effects of immigration; (iii) they can increase social welfare for both sending and receiving communities; (iv) they are compatible with both open and closed borders approaches to immigration.

Gary Becker^[Becker, 1997 IEA] first introduced the idea for an immigration market. He suggested that countries would benefit from charging a market price for immigration ($50,000 in his seminal example) because they would attract the individuals most likely to succeed, i.e. those who expect positive returns to migration, and the revenue raised with this measure would be used to lower other taxes. Occupations with labor shortages could command lower prices and poor people could borrow the money against future earnings and thus would not be excluded from the market. I develop Becker's^[Also discuss Julian Simon] argument further by discussing the compensatory mechanism and the welfare improvement when compared to existing policies.

The moral defense of citizenship markets was recently debated by Javier Hidalgo^[Hidalgo, 2016] and Christopher Freiman,^[Freiman, 2017] in which they put forward the argument in favor of a public and a private citizenship market. I modify their proposal and suggest a market in temporary visas in which the government is the monopolistic producer. I show that this is an improvement compared to previous proposals and that, indeed, a visa market could be implemented as of this moment.

The remaining of this paper is as follows. Section [2](#clarification) presents the motivation for this paper. In section [3](#section1), I compare the discriminatory elements of both visa markets and existing policies; in section [4](#section2), I sketch compensatory mechanisms; in section [5](#section3), I show how markets can produce net welfare both for sending and receiving communities; section [6](#section4) discusses how such markets can adjust to both open and closed borders approaches to immigration; section [7](#conclusion) concludes.

# Motivating a Market for Visas {#clarification}

The premises motivating this article are the following:

  1. Citizens vest governments with the power to make and enforce policy in their best interest.
  2. Any policy which improves the welfare of citizens is welcome, regardless of the status quo.
  3. An immigration policy improving welfare thus can be adopted in lieu of, or in addition to, existing policies.

If these premises were not reasonable, then there would be no need for changing current immigration policies and the debate would be irrelevant. No one would raise objections to premise one. In principle, if just one community of people has vested a government with the power to rule in its best interest, there is reason to believe that any society can do the same; the United States is one evidence of such case. There are incidental reasons, i.e. special circumstances, preventing governments from acting in their citizenry's best interest but they do not invalidate the general premise. Premise two relies on the plausible assumption that anyone is willing to accept something better than what they currently have and that comes at no cost to them. The eventual decisions on whether to trade it up or not remains subject to empirical testing of individual and collective preferences, but in principle all  improvement proposals are welcome. Premise three then follows from one and two and provides the moral ground for the discussion of new immigration policy proposals. If governments have the ability to make and enforce policy in the interest of its citizenry, and an welfare improvement is such an interest, then it is straightforward that a market policy for immigration can be adopted as an improvement or replacement of existing policies. In this case, thus, what is left to prove is whether immigration markets can improve the welfare of citizens receiving migrants in their communities.

That said, I move on to clarifying what the immigrant market proposal in this paper is and what it is not.

First, it should be clear that my goal is showing that an immigration market, and more specifically a market for temporary visas, is permissible in practice this day and age. This is an important departure from Javier Hidalgo,^[explain Hidalgo's point] who claims that selling citizenship might be impermissible if we accept that any type of immigration restriction is unfair. I claim that a market for visas is not limited by our views on the morality of immigration restrictions. In fact, a full-fledged embrace of market reasoning shows that a market for visas is compatible with both open and closed borders approaches to immigration, as I demonstrate in section [6](#section4). Nonetheless, the other arguments developed by Hidalgo against the objections to citizenship markets (i.e. the sale of citizenship changes its value to worse, it corrupts civic norms, and the unfairness imposed on poor foreigners) also hold for the purposes of this paper.

Second, my defense of a market for visas is not equivalent to a defense of free and unregulated market for visas. In contributing the utilitarian approach, I acknowledge the existence of market failures in immigration policy that require government intervention for improvement of social welfare. In particular, I claim that market power, information asymmetry, public goods, and externalities are all present in the market I propose. As such, government regulation is perfectly compatible with cash-for-visa systems. Rather than an unconditional defense of markets, the point is that societies would benefit greatly from this type of market; whether markets are always better is beyond the scope of this study.

I lastly claim that visa^[I am defining visa as the right to enter, leave, or stay in a country for a specific period of time.] markets are marginally better than citizenship markets. In Gary Becker's original proposal, he talks of a fee paid in exchange for the right to immigrate, but makes no further clarification on whether these are temporary or permanent rights. Hidalgo and Freiman specifically discuss citizenship sale. Though I do not oppose the cash-for-citizenship scheme, I believe that temporary visas extending certain rights and obligations to non-citizens are better because they do not infringe upon the right to exclude and are thus compatible with both open and closed border approaches to immigration justice.

Let me address this point carefully. The collective right to exclude should be preserved if the market proposal is to be compatible with arguments in favor of immigration restrictions.^[This point is irrelevant for open border advocates because they do not agree that the individual right to exclude extends naturally to the collective right to exclude. For more on this, please see: Huemer, The Right to Move Versus the Right to Exclude 2017, Wellman 2008 and Fine 2010] David Miller^[Miller find reference] justifies limits to immigration under two arguments: preserving culture and controlling population. According to Miller, a common public culture is necessary because it constitutes the political identity of a community of individuals and it supports valuable social goals; moreover, Miller believes that a right to immigration removes the control societies have over the continuity of their common culture. Secondly, Miller claims that population size should be of government concern as it stretches resources thin, both at the national and at the global level.

Whether I agree with Miller is irrelevant. What is relevant, however, is the extent to which a market for immigration can preserve control over cultural change and does not impose excessive burden on national resources. If these two conditions are met, my proposal remains compatible with immigration restrictions. The solution to both objections is the adoption of temporary permits to enter, leave, or stay in a country's territory for a finite period of time -- in other words, visas. A temporary visa does not remove control of cultural change neither imposes excessive burden on resources because it limits the amount of time any single receiving community will be exposed to either problem. It allows for adjustments to immigration flows if societies feel that cultural change or use of resources is not occurring in accordance with their expectation. In the absence of limits on visa (or citizenship) sales, which I discuss in section [6](#section4), a temporary permit is the only way to morally preserve the right to exclude. Henceforth, I focus exclusively on visa, rather than citizenship, markets. I discuss each of the four pillars supporting the market for visas in subsequent sections.

# Argument 1: Visa markets are no less discriminatory than existing policies {#section1}

The first claim in favor of a market for visas is that it is not any less discriminatory than existing immigration policies. If we agree that some forms of immigration discrimination are permissible, and that immigration markets do not discriminate any more than any of the existing policies, then we can straightforwardly conclude that market for visas can be adopted immediately as immigration policies. The detailed structure of the argument follows:

  1. A market for visas is a discriminatory policy.
  2. Some forms of immigration discrimination are permissible.
  3. In fact, there are certain discriminatory immigration policies currently enacted.
  4. A market for visas does not excessively discriminate beyond certain existing immigration policies.
  5. Therefore, the adoption of a market for visas is consistent with currently enacted, and morally acceptable, discriminatory immigration policies.

Discrimination is defined in the usual form. A person A discriminates against a person B for the fact that B does not possess Z, whether Z is a personal characteristic or a material good. Discrimination is naturally extended from the individual to the state as it treats individuals differently on the basis of having a certain characteristics or possessing a certain material good. In the United States, social programs are only extended to the people lacking a certain level of material resource (e.g. food stamps); similarly, teenagers are denied admission to advanced courses if they do not meet a minimum level of educational achievement (e.g. advance placement classes in high school; honors courses in college). A market for visas is discriminatory in that it does not assign permits to entry, stay, or leave a country if the prospective applicant does not have enough material resources to pay the market price for the visa.

I proceed to show that certain discriminatory policies are permissible. First, I recognize that certain forms of discrimination find no moral ground amongst political philosophers. If we accept Miller's^[Miller Journal of Political Philosophy] account that immigration is a quasi-contractual agreement between non-migrants and migrants, then it is impermissible to discriminate on the basis of religion, ethnicity, gender, etc. because the right to equal treatment on such basis should be extended to migrants as well. Blake^[San Diego Law Review] claims, however, that certain categories of differentiation are permissible, as long as accompanied by discrimination justification that can be reasonably accepted by excluded migrants. The first such reason is *economic success*. State can morally exclude prospective migrants on the basis of their potential contribution to the receiving countries. If countries have to choose whom to exclude amongst a pool of individuals, with no right of entry, and such immigrants have different capabilities in terms of economic contributions, then it is uncontroversial that their potential contribution is a fair ground for differentiation. Since this economic value does not exist in the absence of the individual given the right of entry, then both Rawlsian and utilitarian justice support such differentiation as it unconditionally increases the overall wellbeing of the receiving society.

The second principle is *political integration*. Since States would legitimately promote the advancement of political institutions, and some individuals have more affinity with such institutions, it would be reasonable to exclude those who share relatively fewer values with those of the societies they wish to migrant. Note first that my argument here departs from that of Miller as I accept that political affinity can be a basis for differentiation even if the welcoming societies are not democratic. The freedom of association, and that of rejecting association, is not contingent on democracy. Second, this claim is also independent of the level of affinity of each individual migrant, which is a valuable discussion nonetheless, but irrelevant for my argument. As long as there are two or more prospective migrants, any *relative* rank of affinity suffices for reasonable exclusion. Thus, using Blake's argument, I claim that certain discriminatory immigration policies are permissible.^[See MacKay (2016) for a more comprehensive discussion of one such policy, e.g. skill-selective immigration.]

Premise 3 then holds if there are any examples of immigration discrimination on the basis of economic success or political integration. In fact, there are multiple instances of such policies. In the United States alone, the H1-B and the EB-5 visa programs are but two instances of immigration policies that seek to advance the United States economic prosperity by selecting candidates who possess valuable skills and resources to make domestic investments. Canada, Australia, Germany, the United Kingdom are other countries where similar programs exist. In addition, the national and international political asylum statute are evidence of such policies. By granting entry to individuals who are being persecuted for political reasons in their home country, a receiving nation is granting the right of entry to individuals with whom it shares a common ground of political values that does not threaten pre-existing political integrity. If any of such policies is morally acceptable, and the motivation for visa markets is correct, then any discriminatory, but welfare-increasing, immigration policy can be reasonable adopted.

This leads to premises 4 and 5, according to which markets for visas do not excessively discriminate against prospective migrants and thus could be adopted immediately. The argument is relatively straightforward. Suppose you are a renowned scholar who wants to take up a faculty job in the United States. The program best suited to your situation is the H1-B, under which high-skills individuals are welcome in the interest of the country's scientific community. Besides submitting proper documentation of skills and professional background, you and your employer need to pay processing fees amounting to more than $1,000. The fee effectively represents a monetary discrimination against highly-skilled foreign workers, as no worker will be allowed entry if these fees are not paid. As such, these policies establish a double discrimination procedure in which the fees and the documentation are differentiating prospective migrants; at the moment,these policies place excessive weight on documentation rather than the monetary exchange. A market for visas is a reordering of the documentation and the monetary priorities when governments are issuing immigration permits, with the benefit of market transparency brought about by monetary exchange. The price charged for visas, or visa processing fees, bears no relationship to the morality of price mechanisms.^[Jason Brennan and Peter Jaworski develop this argument in (...BOOK...), where they claim that the exchange of goods and services for money does not change the morality of good and service being exchanged. Anything that is immoral in a market exchange would also be immoral if exchanged in another form.] Therefore, a market for visas cannot excessively discriminate against migrants if there are less clear monetary exchanges built into existing policies.

Some might object to this policy because of market dynamics. If governments let market forces dictate the price of visas, then an unreasonably high price might effectively discriminate against people who do not possess the resources to buy their temporary visa. This is an unfounded claim for the basic reason that governments are not obliged to let prices fluctuate neither set prices at any certain level. In economic theory, only under special circumstances a monopolist producer of visas (government) would set prices and quantity strictly according to market forces. At no point have I suggested a free market for visas, in which case these claims would be relevant.

A second objection would be the fact that very poor migrants are always priced out of visas regardless of price levels simply because there are too many poor people who cannot afford a visa in any case. This is an interesting objection, but it is better addressed in section [6](#section4), in which I discuss how markets for visas are compatible with open and closed borders arguments.

# Argument 2: Visa markets create compensation mechanisms for negatively affected communities {#section2}

The first utilitarian contribution in this essay is the claim that visa markets create compensation mechanisms for communities that are negatively affected by immigration. Though classic utilitarianism might not be concerned with the distribution of net benefits, I adopt a realistic approach in which preferences for redistribution are also an important determinant of individual wellbeing and collectively determine net utility. In fact, there is substantial empirical evidence in support of preferences for redistribution in the social sciences.^[Forsythe, 1994. Andreoni et al, 2003. Camerer, 2003. Alesina and Giuliano, 2011.] ;^[Alesina and Giuliano 2011 suggest that inequality can affect individual utilities indirectly -- an increase in inequality causes crime rates to rise such that individuals are more likely to experience a crime event -- or directly -- people just genuinely do not like poverty and feel bad that others have to live such life.] This egalitarian twist, however, does not take away from the classic utilitarian analysis in section [5](#section3).

Suppose there is a new Mariel boatlift-like event but this time all boats are full of skilled migrants. In the course of six months, there are 125,000 Cuban software engineers seeking jobs in Miami, FL. At the very least, these immigrants need housing and food. Immediate shortages are likely such that Miami residents bear most of the negative effects of immigration (compared to someone living in Tallahassee, for instance). As long as immigration is spatially concentrated, some regions bear relatively more of the consequences than others.^[Note there are no constraints on the type of effect neither on its duration. It could well be that city residents dislike newcomers or that, in the long term, these impacts fade out. The spatial concentration of migrants suffices for creating the disparity in effects.] Therefore, immigrants impose an unconditional and immediate burden on the receiving community.

How best to address the immediate problem? State and city governments could find public housing for these engineers. Grocery stores or residents could set-up food drives and deliver food to public housing units. Whatever alternative we find, however, is based on redistribution of resources from the community to the migrants. Using state funds to house migrants, for instance, is even further redistribution from taxpayers in regions unaffected by migration to Miami and the software engineers. Note that these migrants are not entitled to such transfers. Florida residents have not wronged the migrants in any way such that no compensation claims exist and migrants have willingly decided to leave Cuba and tacitly accepted the consequences of their actions, including sleeping on the streets. If anything, the harm imposing agents are the engineers and they should compensate Miami residents. A market for visas creates such mechanism without disproportionately harming the migrants. The argument is structured as follows:

  1. A spatially concentrated flow of immigrants can impose harm on the residents of the receiving community.
  2. In the presence of harm, immigrants should compensate non-migrants.
  3. The redistribution of visa market revenues are one such compensation mechanism.
  4. Therefore, markets for visas are welfare-increasing for immigrant-receiving communities.

Premise 1 is described in the paragraphs above. Robert Nozick's well-established definition of compensation supports premise 2.^[According to Nozick, an individual A should compensate an individual B if A's action Y crossed the boundary of B's individual domain without B's consent. The compensation for A's action is the reestablishment of B's wellbeing if A had not done Y.] Premise 3 follows from the 


The economic version of the compensation principle requires that gainers compensate losers for their loss if the former remain at least as well off as before. If this 

# Argument 3: Visa markets can increase social welfare for sending and receiving communities {#section3}
 
# Argument 4: Visa markets are compatible with both open and closed borders approaches to immigration {#section4}

# Conclusion {#conclusion}

