---
title    : 'Markets for Visas:'
subtitle : A Radical and Fair Approach to Immigration
author   : Andre Assumpcao
institute: UNC-Chapel Hill
date     : March 29\textsuperscript{th}, 2019
output   : 
  beamer_presentation:
    theme     : 'Madrid'
    colortheme: 'default'    
header-includes:
  - \usepackage{hyperref}
  - \hypersetup{colorlinks = true, linkcolor = white, urlcolor = blue}
  - \usepackage{graphicx}
---

# Motivation {#motivation}

- Super Bowl vs. USCIS example. \

- Gary Becker: **immigration markets.** \

- Javier Hidalgo: ***public* sale of citizenship.** \

- Christopher Freiman: ***private* sale of citizenship.** \

- This paper:
\bigskip 
    #. Shifts the emphasis from citizenship to **visa markets**;
    
    #. **Develops the utilitarian argument** for visa markets.

# Argument 1: Visa markets are no less discriminatory than existing policies {#arg1}

  #. A market for visas is a discriminatory policy. \
  
  #. Some forms of immigration discrimination are permissible. \
  
  #. In fact, there are certain discriminatory immigration policies currently enacted. \
  
  #. A market for visas does not excessively discriminate beyond certain existing immigration policies. \
  
  #. Therefore, the adoption of a market for visas is morally equivalent to current discriminatory immigration policies.

# Argument 2: Visa markets create compensation mechanisms for negatively-affected communities {#arg2}

  #. A spatially concentrated flow of immigrants can impose harm on the residents of receiving communities. \

  #. In the presence of harm, immigrants should compensate non-migrants. \

  #. Markets for visas create an additional source of government revenue which can be used to compensate for immigration harms with no effect on other expenditures. \

  #. Therefore, markets for visas are welfare-increasing for immigrant-receiving communities.

# Argument 3: Visa markets quickly increase social welfare for sending and receiving communities {#arg3}

**Empirical claims:**
 
  #. Immigration increases productivity and scientific innovation (destination countries). \
  
  #. Immigration increases remittances and investments in human capital (source countries). \
  
  #. Immigration increases trade flows (source and destination countries). \
  
**Visa markets:**

  #. Incentivize immigration (bring SMg closer to PMg). \

  #. Allow for quicker realization of welfare gains (from long to short term benefits).
    
# Argument 4: Visa markets are compatible with both open and closed borders approaches to immigration {#arg4}

- **Positive prices:** right to exclude is preserved. \
\bigskip
    + The establishment of loan and tax liabilities programs prevents unfair discrimination against the poor. \
\bigskip
- **Zero prices:** right to exclude is absent.  

# Conclusion

- This paper is **not**... \
\bigskip
    #. ...asking for **all immigration** policies to be replaced by markets. \
\medskip
    #. ...an argument in favor of **unregulated, free markets** for visas. \
\medskip
    #. ...suggesting any specific **market design**. \
\bigskip    
- This paper is... \
\bigskip
    #. ...claiming that **visa markets are better** than some existing immigration policies. \
\medskip    
    #. ...bringing together **normative and utilitarian** arguments for visa markets. \
\medskip
    #. ...suggesting **visa markets should be seriously considered** as immigration policy options.

# Thank you!

Andre Assumpcao \
Ph.D. Candidate \
Department of Public Policy \
The University of North Carolina at Chapel Hill \
[https://aassumpcao.github.io](https://aassumpcao.github.io)